<?php

/**
 * This is the model base class for the table "state".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "State".
 *
 * Columns in table "state" available as properties of the model,
 * followed by relations of table "state" available as properties of the model.
 *
 * @property string $code
 * @property string $name_en
 * @property string $name_hi
 *
 * @property Corporation[] $corporations
 * @property District[] $districts
 */
abstract class BaseState extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'state';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'State|States', $n);
	}

	public static function representingColumn() {
		return 'code';
	}

	public function rules() {
		return array(
			array('code', 'required'),
			array('code', 'length', 'max'=>2),
			array('name_en, name_hi', 'length', 'max'=>45),
			array('name_en, name_hi', 'default', 'setOnEmpty' => true, 'value' => null),
			array('code, name_en, name_hi', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'corporations' => array(self::HAS_MANY, 'Corporation', 'state_code'),
			'districts' => array(self::HAS_MANY, 'District', 'state_code'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'code' => Yii::t('app', 'Code'),
			'name_en' => Yii::t('app', 'Name En'),
			'name_hi' => Yii::t('app', 'Name Hi'),
			'corporations' => null,
			'districts' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('code', $this->code, true);
		$criteria->compare('name_en', $this->name_en, true);
		$criteria->compare('name_hi', $this->name_hi, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}